#
#  Makefile
#

#
#  RTEMS_MAKEFILE_PATH is typically set in an environment variable
#

include $(RTEMS_MAKEFILE_PATH)/Makefile.inc

include $(RTEMS_CUSTOM)
include $(PROJECT_ROOT)/make/leaf.cfg

all:    

print_cc:
	@echo $(CC_FOR_TARGET) $(GCCSPECS) $(CPU_CFLAGS)

print_ar:
	@echo $(AR_FOR_TARGET)

print_ranlib:
	@echo $(RANLIB)
