/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mil_navy_nrl_protolib_ProtoPipe */

#ifndef _Included_mil_navy_nrl_protolib_ProtoPipe
#define _Included_mil_navy_nrl_protolib_ProtoPipe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mil_navy_nrl_protolib_ProtoPipe
 * Method:    createProtoPipe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_protolib_ProtoPipe_createProtoPipe
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_protolib_ProtoPipe
 * Method:    listen
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_mil_navy_nrl_protolib_ProtoPipe_listen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mil_navy_nrl_protolib_ProtoPipe
 * Method:    read
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_mil_navy_nrl_protolib_ProtoPipe_read
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     mil_navy_nrl_protolib_ProtoPipe
 * Method:    connect
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_mil_navy_nrl_protolib_ProtoPipe_connect
  (JNIEnv *, jobject, jstring);

/*
 * Class:     mil_navy_nrl_protolib_ProtoPipe
 * Method:    write
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_protolib_ProtoPipe_write
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     mil_navy_nrl_protolib_ProtoPipe
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_protolib_ProtoPipe_close
  (JNIEnv *, jobject);

/*
 * Class:     mil_navy_nrl_protolib_ProtoPipe
 * Method:    doFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mil_navy_nrl_protolib_ProtoPipe_doFinalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
