#
# Linux wxWindows Makefile definitions
#

# 1) Where to find the wxWindows files
WX_FLAGS = `wx-config --cxxflags`
WX_LIBS = `wx-config --libs`

# 2) System specific additional libraries, include paths, etc
#    (Where to find X11 libraries, etc)
#
SYSTEM_FLAGS = 
SYSTEM_INCLUDES = 
SYSTEM_LIBS = 
SYSTEM_REZ = touch

SYSTEM_HAVES = -DLINUX -DHAVE_IPV6 -DHAVE_GETLOGIN -DHAVE_LOCKF -DHAVE_DIRFD \
-DHAVE_ASSERT $(NETSEC)

SYSTEM = linux
CC = g++
RANLIB = ranlib
AR = ar

include Makefile.common
